name: Mirror to GitLab

on:
  push:
    branches:
      - main
  delete:

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/bighead.0-group/Zelda-LA-DX-HD-Updated.git
          git push gitlab --mirror